language: python
python:
  - "2.7"

# command to let run a real GUI application or web browser
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

# command to install dependencies
install: "pip install -r requirements.txt"

  
before_script: 
  - "flake8 --ignore=F403 sched tests/features"

# command to run tests
script: 
  - lettuce tests/
  - coverage run --omit="*site-packages*" testsUnit.py
  - coverage report -m
  - nosetests --with-doctest -s sched
