language: python
python:
  - "2.7"

# command to install dependencies
install: "pip install -r requirements.txt"
before_script: 
  - "flake8 --ignore=F403 sched"

# command to run tests
script: 
  - coverage run --omit="*site-packages*" testsUnit.py
  - coverage report -m
  - nosetests --with-doctest -s sched
